---

- name: "Users | Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined and fubarhouse_user is undefined

- name: "Users | Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined and fubarhouse_user is undefined

- name: "Users | Get $HOME"
  shell: "echo $HOME"
  register: shell_home_dir
  when: fubarhouse_user_dir is undefined

- name: "Users | Set $HOME"
  set_fact:
    fubarhouse_user_dir: "{{ shell_home_dir.stdout }}"
  when: fubarhouse_user_dir is undefined