---

- name: "Virtual hosts | NGINX | Create virtual hosts"
  become: yes
  become_user: root
  template:
    src: "../templates/vhosts/nginx.conf.j2"
    dest: "/etc/{{ fubarhouse_webserver }}/{{ item[0] }}/{{ item[1].name }}.conf"
    owner: root
    group: root
    mode: 0777
  with_nested:
  - ['conf.d', 'sites-available', 'sites-enabled']
  - "{{ fubarhouse_vhosts }}"